apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: appdeployer-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: appdeployer-issuer
    solvers:
      - http01:
          ingress:
            class: nginx