# permissions for end users to view appdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appdeployer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-operator
    app.kubernetes.io/part-of: deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeployer-viewer-role
rules:
- apiGroups:
  - deployer.rappizs.com
  resources:
  - appdeployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployer.rappizs.com
  resources:
  - appdeployers/status
  verbs:
  - get
