---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deployer.rappizs.com
  resources:
  - imagedeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployer.rappizs.com
  resources:
  - imagedeployers/finalizers
  verbs:
  - update
- apiGroups:
  - deployer.rappizs.com
  resources:
  - imagedeployers/status
  verbs:
  - get
  - patch
  - update
