apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-local
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rappizsolt@gmail.com
    privateKeySecretRef:
      name: letsencrypt-local
    solvers:
      - http01:
          ingress:
            class: nginx