apiVersion: deployer.my.domain/v1
kind: ImageDeployer
metadata:
  labels:
    app.kubernetes.io/name: imagedeployer
    app.kubernetes.io/instance: imagedeployer-sample
    app.kubernetes.io/part-of: basic-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: basic-operator
  name: imagedeployer-sample
spec:
  # TODO(user): Add fields here
