name: Build and Push Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  OPERATOR_IMAGE_NAME: ${{ github.repository }}
  NGINX_IMAGE_NAME: nginx-hello

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Test
      run: make test
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
 
    - name: Build and push Operator image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/rappizs/${{ env.OPERATOR_IMAGE_NAME }}:latest

    - name: Build and push Nginx image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.nginx
        push: true
        tags: ${{ env.REGISTRY }}/rappizs/${{ env.NGINX_IMAGE_NAME }}:latest

