name: Run Tests

on:
  push:
    branches-ignore:
      - main
env:
  REGISTRY: ghcr.io
  OPERATOR_IMAGE_NAME: ${{ github.repository }}
  NGINX_IMAGE_NAME: nginx-hello

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Test
      run: make test

    - name: Build Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: |
          ${{ env.REGISTRY }}/rappizs/${{ env.OPERATOR_IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/rappizs/${{ env.NGINX_IMAGE_NAME }}:latest
        dockerfile: |
          Dockerfile
          Dockerfile.nginx
